### PR TITLE
Added the ability to inspect the headers on a generic event

### PR DESCRIPTION
**Pull request by shaneshort**

### CODE REVIEW

**Review by benlangfeld — CHANGES_REQUESTED** [review]
This doesn’t look like it makes any difference. What are you trying to achieve?

**Comment by shaneshort** [comment]
Allows you to access the raw headers inside a generic event. Best I could tell this isn't available by default.

**Comment by benlangfeld** [comment]
Defining a method which calls super is the same thing as not defining it.

**Comment by benlangfeld** [comment]
The headers are already available. This change doesn’t have any effect.

**Pull request closed without merging**
